before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
    arm64: ARM_64-bit
    arm: ARM_32-bit
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
snapcraft:
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
    arm64: ARM_64-bit
    arm: ARM_32-bit
  publish: true
  summary: A command line utility that forwards stdin to Twilio for alerting.
  description: |
    A command line utility that forwards stdin to Twilio for alerting.
  grade: stable
  confinement: strict
