before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
snapcraft:
  publish: true
  summary: A command line utility that forwards stdin to Twilio for alerting.
  description: |
    A command line utility that forwards stdin to Twilio for alerting.
  grade: stable
  confinement: strict
